---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/11/30 4:36 下午
---

function hello()

    print("hello world")
end

hello();

function testWhile()
    local i = 0
    local max = 10
    while i <= max do
        print(i)
        i = i + 1
    end

end

testWhile();

function testMap()

    lucy = { name = 'xiao6', age = 18, height = 165.5 }

    --xiao6.age=35

    print(lucy.name, lucy.age, lucy.height)

    --print(xiao6)

end

testMap();

function testClass()

    person = { name = 'xiao6', age = 18 }

    function person.eat(food)

        print(person.name .. " eating " .. food)

    end
    person.eat("xxoo")
end

testClass();
