---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021/11/30 5:40 下午
---

function getValue()
    local key=KEYS[1]
    local list=redis.call("get",key)
    return list
end
